---
- name: install | Creating Nexus User
  user:
    create_home: false
    home: /nonexistent
    name: nexus
    shell: /usr/sbin/nologin
    state: present
    system: true
  become: true

- name: install | Downloading Nexus Repo OSS
  unarchive:
    src: "{{ nexus_repo_oss_dl_url }}"
    dest: "{{ nexus_repo_oss_install_dir }}"
    remote_src: true
    creates: "{{ nexus_repo_oss_install_dir + '/nexus-' + nexus_repo_oss_version|string + '-01' }}"
  become: true

- name: install | Setting Permissions On Nexus Repo Dirs
  file:
    group: nexus
    owner: nexus
    path: "{{ item }}"
    state: directory
    recurse: true
  become: true
  loop:
    - "{{ nexus_repo_oss_install_dir + '/nexus-' + nexus_repo_oss_version|string + '-01' }}"
    - "{{ nexus_repo_oss_install_dir + '/sonatype-work' }}"

- name: install | Configuring Nexus Repo OSS Service (upstart|sysvinit)
  file:
    src: "{{ nexus_repo_oss_install_dir + '/nexus-' + nexus_repo_oss_version|string + '-01/bin/nexus' }}"
    dest: /etc/init.d/nexus
    state: link
  become: true
  when: >
    ansible_service_mgr == "upstart"
    or ansible_service_mgr == "sysvinit"

- name: install | Ensuring Nexus Repo OSS Service Is Started and Enabled (upstart|sysvinit)
  service:
    name: nexus
    state: started
    enabled: true
  become: true

- name: install | Configuring Nexus Repo OSS Service (systemd)
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
  become: true
  when: ansible_service_mgr == "systemd"

- name: install | Ensuring Nexus Repo OSS Service Is Started and Enabled (systemd)
  systemd:
    name: nexus.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
  when: ansible_service_mgr == "systemd"

- name: install | Waiting For Nexus Repo OSS Service To Start
  wait_for:
    port: 8081

- name: install | Checking For Initial Nexus Default Admin Password
  stat:
    path: "{{ nexus_repo_oss_install_dir + '/sonatype-work/nexus' + nexus_repo_oss_version.split('.')[0]|string + '/admin.password' }}"
  register: nexus_repo_oss_default_pass_check

- name: install | Capturing Nexus Admin Password
  slurp:
    src: "{{ nexus_repo_oss_install_dir + '/sonatype-work/nexus' + nexus_repo_oss_version.split('.')[0]|string + '/admin.password' }}"
  register: _nexus_repo_oss_temp_pass
  when: nexus_repo_oss_default_pass_check['stat']['exists']

- name: install | Setting Admin Password Fact
  set_fact:
    nexus_repo_oss_temp_pass: "{{ _nexus_repo_oss_temp_pass['content'] | b64decode }}"
  when: nexus_repo_oss_default_pass_check['stat']['exists']

- name: install | Displaying Nexus Admin Password
  debug:
    msg: "Admin password: {{ nexus_repo_oss_temp_pass }}"
  when: nexus_repo_oss_default_pass_check['stat']['exists']
