---
- name: Converge
  hosts: all
  roles:
    - role: ansible-nexus-repo-oss
  post_tasks:
    - name: Ensuring Nexus Repo Manager is up and running
      uri:
        url: http://localhost:8081
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
